services:
  api:
    build:
      context: ./
    image: shopapi:newest
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
