services: 
  api: 
    image: gorandockerid/shopapi
    build: .
    command: "npm start"
    ports: 
      - "3000:3000"
    depends_on: 
      - "mongo"
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    